spring.application.name=SpringSecurityExample


# set the default user name and password for spring security
spring.security.user.name=rahul
spring.security.user.password=284380


spring.datasource.url= jdbc:postgresql://localhost:5432/springsecurityexample
spring.datasource.username=postgres
spring.datasource.password=1234
